# Generated by Django 5.2.10 on 2026-02-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_alter_course_id_alter_lesson_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
